model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192 
    ckpt_path: 'ckpt/vqgan.ckpt'
    ddconfig:
      double_z: False
      z_channels: 256 
      resolution: 256
      in_channels: 3 
      out_ch: 3 
      ch: 128 
      ch_mult: [ 1,1,2,2,4]  
      num_res_blocks: 2
      attn_resolutions: [] 
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10001
        disc_weight: 0.5
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 10
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: data/train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: data/val.txt
        size: 256

train:
  save_dir: ckpt
  save_weights_only: True
  monitor: "val_rec_loss"
  every_n_train_steps: 100
  filename: "best-{epoch}-{step}-{val_rec_loss:.2f}"
  mode: "min"
  save_top_k: 1
  num_gpu: 4
  num_nodes: 1
  max_epochs: 1
  val_check_interval: 99